apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: mynifi
  selfLink: /api/v1/namespaces/default/services/mynifi
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: mynifi
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
