apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    run: mynifi
  name: mynifi
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/mynifi
spec:
  replicas: 1
  selector:
    matchLabels:
      run: mynifi
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: mynifi
    spec:
      containers:
      - image: awgouge/nifi
        imagePullPolicy: Always
        name: mynifi
        ports:
        - containerPort: 8080
          hostPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: mynifi
  selfLink: /api/v1/namespaces/default/services/mynifi
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: mynifi
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
